### ISSUE TITLE
Realtime-Heatmap chart doesn't apply data while open another site

### ISSUE THREAD

**Issue by irawan2018** [juijs/www.jui.io#22]
When I back to heat-map chart after i open another site in another tab/window, heat-map chart doesn't apply data.
Please refer to the link: http://chartplay.jui.io/?p=realtime_heatmap 
![image](https://user-images.githubusercontent.com/45579586/50372292-bc454880-05fe-11e9-924c-3b81cbba824b.png)

**Comment by seogi1004** [comment]
@irawan2018 It was a bug that occurred by generating too much sample data.
When updating chart data, it is better to use 'requestAnimationFrame' instead of 'setInterval'.
(PS: Do not trust the sample too much)

**Comment by irawan2018** [comment]
@seogi1004 could you please give me sample to use 'requestAnimationFrame'?

**Comment by seogi1004** [comment]
@irawan2018 Please check the sample below.

https://github.com/juijs/jui-graph/blob/master/examples/equalizer.html
