### ISSUE TITLE
Developing Screen Gallery

### ISSUE THREAD

**Issue by seogi1004** [juijs/www.jui.io#9]
컴포넌트와 차트 조합으로 좀 더 심화된 샘플을 제공하는 메뉴

**Comment by seogi1004** [comment]
gallery 디렉토리 만듬...
feature/gallery 체크아웃 받으셈!

**Comment by seogi1004** [comment]
갤러리에 들어갈 샘플은 "gallery/샘플명" 형태로 들어가면 됩니다.
현재는 예전에 진호형이 만들어둔 admintool이 있어요.

**Comment by easylogic** [comment]
갤러리 기본 구조 잡았음 

디자인 의견 주세요.

**Comment by incleaf** [comment]
리스트에서 제목이랑 설명이 스타일이 같은데 구분이 되면 좋을 것 같네요!

**Comment by seogi1004** [comment]
@incleaf 좋은 의견입니다! 안그래도 조금 변경을 할까했었어요. ㅋㅋ

**Comment by easylogic** [comment]
아직 디자인은 적용 전이니 많은 의견 주심 감사하겠습니다.

**Comment by easylogic** [comment]
갤러리 리스트에서 제목을 뺐습니다.  

iframe 과 description 만 출력이 됩니다.
